;PROGRAMA QUE DIBUJA UNA LINEA DE COLOR VERDE

org 100h ; código COM
section .text

MOV AH, 00H ;MODO VIDEO (PANTALLA)
MOV AL, 12H ;MODO GRAFICO 640X480
INT 10H ;RUTINA DE LA BIOS

MOV AH, 0CH ;PETICION DEL PUNTO
MOV AL, 02H ;EN COLOR VERDE
MOV BH, 00H ;PAGINA 00
MOV CX, 00H ;COLUMNA 0 

;HACIENDO SUBRUTINA 1
S1: 
    MOV DX, 12CH ;EN LA FILA 300 (INICIO)
    INT 10H ;LLAMA RUTINA DE LA BIOS

INC CX ;SE INCREMENTA CX HASTA...
CMP CX, 0140H ;HASTA EL 320 DECIMAL
JNZ S1 ;REALIZA SALTO A S1 Y SE REPITE HASTA QUE CUMPLA CONDICION

S2:
    MOV AH, 00H ;MODO VIDEO PARA LA LECTURA DEL TECLADO
    INT 16H ;RUTINA DE BIOS PARA TECLADO

CMP AL, 53H ;BUSCA EL INGRESO DE LA LETRA S
JNZ S2 ;MIENTRAS NO ESCRIBA S SALTA A S2
MOV AH, 00H ;MODO TEXTO
MOV AL, 03H ;RESOLUCION DE 25X80
INT 10H ;RUTINA DE LA BIOS PARA MODO TEXTO
INT 20H ; LLAMA DEBUG