;PROGRAMA QUE DIBUJA UN PUNTO NADA MAS EN ALGUNA PARTE DE LA PANTALLA

org 100h ; código COM
section .text

MOV AH, 00h ; MODO VIDEO (PANTALLA)
MOV AL, 12H ; NIDI GRAFICO
INT 10H  ;LLAMA A LA RUTINA DE LA BIOS

MOV AH, 0CH  ;PETICION DEL PUNTO
MOV AL, 0FH ; COLOR BLANCO
MOV CX, 50H ; EN LA COLUMNA 80
MOV DX, 70H ;EN LA FILA 117
INT 10H  ;LLAMA RUTINA DE LA BIOS

;HACIENDO SUBRUTINA
S1: 
    MOV AH, 00H ;MODO VIDEO PARA LECTURA DEL TECLADO
    INT 16H ;RUTINA DE LA BIOS PARA TECLADO

CMP AL, 41H ;COMPARA TECLA A CON CODIGO ASCII
JNZ S1 ;SALTO A S1
INT 20H ;VUELVE A COMANDOS DEL DEBUG
